### ISSUE TITLE
Большая задержка перед отправкой данных

### ISSUE THREAD

**Issue by GigaVik** [Lefey/ad_narodmon_sender#1]
После конфигурирования приложения и запуска апдемона, данные на народмон начинают уходить в лучшем случае через несколько часов. никакой информации ни в логах нет, ни во входящих логах на народмон. 
﻿я подумал может быть после запуска происходит отправка данных и могла  произойти отправка с меньшим интервалом при моем конфигурировании и попадание в бан, после того как приложениеисправно начало отправлять данные,  после перенастройки я подождал 15 минут и запустил, но все равно отправка не происходит в логах пусто, на народмон тоже. оставляю все, через несколько часов 3-5  приходит сообщение от народмон, что пошли данные от меня.
﻿все конфигурации несколько раз перелопатил, логи в апдемоне на уровне debug, тоже ничего внятного не показывают.

**Comment by Lefey** [comment]
Укажите правильную временную зону в файле конфигурации appdaemon.yaml
