### ISSUE TITLE
Not correctly send data

### ISSUE THREAD

**Issue by electro-nic** [Lefey/ad_narodmon_sender#2]
![Screenshot_20210209-071756_Gmail (1)](https://user-images.githubusercontent.com/1056660/107319251-1b000180-6aa7-11eb-8fc1-eddeb22f0b19.jpg)
What in not correctly in script?

**Comment by Lefey** [comment]
Подобные проблемы повторялись?

**Comment by electro-nic** [comment]
Когда вдруг данные от датчика не пришли то на narodmon отправляется unknown. Можно это как-то пофиксить или хотя-бы сделать задержку при перезагрузке. И еще одна хотелка чтобы скрипт как-то запоминал когда отправил данные и не переотправлял чаще чем 5 мин

**Comment by Lefey** [comment]
Проблема ясна, но пока нет времени этим заняться, нужно снова вникнуть в код и продумать как это исправить, когда это будет и будет ли вообще, не могу обещать.
Вообще в планах была идея переделать этот проект на кастомный модуль для homeassistant, чтобы можно было установить через HACS и настроить через графический интерфейс, но это очень долгосрочная идея.
