### ISSUE TITLE
Sending data from multiple sensors

### ISSUE THREAD

**Issue by RipZ** [Lefey/ad_narodmon_sender#4]
Можно ли добавить возможность отправки данных с нескольких датчиков?

**Comment by GigaVik** [comment]
Достаточно просто скопировать /config/appdaemon/apps/narodmon_sender в /config/appdaemon/apps/narodmon_sender_2 и сконфигурировать ../narodmon_sender_2/config.yaml под новый прибор.

**Comment by Lefey** [comment]
@GigaVik @RipZ 
Зачем такие сложности, если такая возможность предусмотрена изначально и даже в примере конфига для примера перечислено несколько датчиков: 
`hass_sensor_entities: sensor.outside_temperature,sensor.outside_humidity,sensor.outside_pressure,binary_sensor.window`

**Comment by GigaVik** [comment]
@Lefey
Это да, я со своей колокольни подумал именно про второй прибор (со своим названием, MACом и периодом отправки.), а не сущность...
